<a href="https://colab.research.google.com/github/rai8896/Pytorch-/blob/main/4.2pytorch_nn_module_Part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Code Flow
- Load the dataset
- Basic Preprocesing
- Training Process
  - Create the Model
  - Forward Pass
  - Loss calculation
  - Back Propogation
  - Parameter Updates
- Model Evoluation

# Improvement
- Building the neural netwpork using nn model
- Using Buiilt in activation function
- Using Built in loss function
- Using Built in Optimizer ex: scoastic gradient decent

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-9.00831255e-01, -1.64690352e+00, -9.25978677e-01, ...,
        -1.24372808e+00, -1.19642727e+00, -9.67384776e-01],
       [-9.03597926e-01, -1.50524279e+00, -9.44016794e-01, ...,
        -1.13003717e+00, -2.68612922e-01, -3.86786139e-01],
       [ 1.66387315e+00,  1.05161714e+00,  2.06273682e+00, ...,
         2.03458440e+00,  3.94475579e+00,  8.83064430e-01],
       ...,
       [ 6.47370709e-02,  1.75295383e+00,  3.78822473e-04, ...,
        -8.88874643e-01, -8.81438201e-01, -1.06712293e+00],
       [ 1.76623999e+00,  3.29379682e-01,  1.82623707e+00, ...,
         1.49533899e+00,  2.60007356e-01, -4.51420920e-01],
       [ 4.32704370e-01, -1.89539036e+00,  4.23272445e-01, ...,
         4.52797880e-01, -5.50855608e-01, -1.10416730e-01]])

In [9]:
y_train

296    B
159    B
78     M
167    M
85     M
      ..
84     B
141    M
462    B
535    M
484    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

### Numpy arrays to PyTorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor

tensor([[-9.0083e-01, -1.6469e+00, -9.2598e-01,  ..., -1.2437e+00,
         -1.1964e+00, -9.6738e-01],
        [-9.0360e-01, -1.5052e+00, -9.4402e-01,  ..., -1.1300e+00,
         -2.6861e-01, -3.8679e-01],
        [ 1.6639e+00,  1.0516e+00,  2.0627e+00,  ...,  2.0346e+00,
          3.9448e+00,  8.8306e-01],
        ...,
        [ 6.4737e-02,  1.7530e+00,  3.7882e-04,  ..., -8.8887e-01,
         -8.8144e-01, -1.0671e+00],
        [ 1.7662e+00,  3.2938e-01,  1.8262e+00,  ...,  1.4953e+00,
          2.6001e-01, -4.5142e-01],
        [ 4.3270e-01, -1.8954e+00,  4.2327e-01,  ...,  4.5280e-01,
         -5.5086e-01, -1.1042e-01]], dtype=torch.float64)

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

In [16]:
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()
X_test_tensor = X_test_tensor.float()
y_test_tensor = y_test_tensor.float()

### Defining the model

In [17]:
import torch.nn as nn

In [18]:
class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out=self.linear(features)
    out=self.sigmoid(out)
    return out



  # def __init__(self, X):

  #   self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True) #X.shape[1] ka mtlb hua 30 kyuki 30 weight dene padenge
  #   self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  # def forward(self, X):
  #   z = torch.matmul(X, self.weights) + self.bias
  #   y_pred = torch.sigmoid(z)
  #   return y_pred

  # def loss_function(self, y_pred, y):
  #   # Clamp predictions to avoid log(0)
  #   epsilon = 1e-7
  #   y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

  #   # Calculate loss
  #   loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
  #   return loss

### Important Parameters

In [19]:
learning_rate = 0.1
epochs = 25

In [20]:
loss_function= nn.BCELoss()

### Training Pipeline

In [22]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])
# optimizer=torch.optim.SGD(model.parameters(), lr=learning_rate)
optimizer=torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1))


  # zero gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()


  optimizer.step()


  # zero gradients       PyTorch में gradients automatically accumulate होते हैं    अगर zero नहीं करोगे → पुराना gradient + नया gradient जुड़ जाएगा ❌
          # model.linear.weight.grad.zero_()
          # model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6293917894363403
Epoch: 2, Loss: 0.49099835753440857
Epoch: 3, Loss: 0.4162713587284088
Epoch: 4, Loss: 0.3694635331630707
Epoch: 5, Loss: 0.33679327368736267
Epoch: 6, Loss: 0.31231170892715454
Epoch: 7, Loss: 0.29305434226989746
Epoch: 8, Loss: 0.2773682475090027
Epoch: 9, Loss: 0.2642517387866974
Epoch: 10, Loss: 0.253058522939682
Epoch: 11, Loss: 0.24335062503814697
Epoch: 12, Loss: 0.23481938242912292
Epoch: 13, Loss: 0.22724004089832306
Epoch: 14, Loss: 0.22044463455677032
Epoch: 15, Loss: 0.21430446207523346
Epoch: 16, Loss: 0.20871923863887787
Epoch: 17, Loss: 0.2036091536283493
Epoch: 18, Loss: 0.19891001284122467
Epoch: 19, Loss: 0.19456925988197327
Epoch: 20, Loss: 0.1905435472726822
Epoch: 21, Loss: 0.18679653108119965
Epoch: 22, Loss: 0.18329770863056183
Epoch: 23, Loss: 0.18002095818519592
Epoch: 24, Loss: 0.17694400250911713
Epoch: 25, Loss: 0.1740475594997406

### Evaluation

In [23]:
# model evaluation
with torch.no_grad():
  y_pred = model(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5366266369819641